baseurl         = "https://juliorcx.github.io/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
#canonifyurls    = true

[params]
  title       = "Julio RC Design"
  subtitle    = "Creating new ideas since 2019"
#copyright   = "© 2019"

  cover       = "uploads/main.jpg"
  description = "CAD design and Data analysis for your projects"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

#twitterName = "faketryghost"
#fbName = "fakeghost"
  githubName = "juliorcx"
#linkedinName = "eueung"
#mediumName = ""

  logo = ""
  orgName = "JRC"
#orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  showSupport = true

  author = "Julio RC"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "Nanterre, FR"
  authorWebsite = "https://juliorcx.github.io"
  authorDescription = "CAD designer, Data Analyst"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Main"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Services"
  url = "/services/"
  weight = 150

[[menu.main]]
  name = "Project"
  url = "/project/"
  weight = 100

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 95

[[menu.main]]
  name = "Contact"
  url = "/tags/contact/"
  weight = 90


